<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\modules\workflow\models\SwStatus $model
*/

$this->title = 'Sw Status ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Sw Statuses', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id, 'workflow_id' => $model->workflow_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>

<?php echo $this->render('@app/modules/workflow/views/menu/_menu'); ?>

<div class="giiant-crud sw-status-view">

    <div class="clearfix crud-navigation">
    <!-- menu buttons -->
    <div class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'id' => $model->id, 'workflow_id' => $model->workflow_id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
    </div>
    <div class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List SwStatuses'), ['index'], ['class'=>'btn btn-default']) ?>
    </div>

    </div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <?= $model->id ?>
        </div>

        <div class="panel-body">



    <?php $this->beginBlock('app\modules\workflow\models\SwStatus'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'id',
        'label',
        'created_by',
        'updated_by',
        'created_at',
        'updated_at',
        'deleted_at',
        'workflow_id',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id, 'workflow_id' => $model->workflow_id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('SwTransitions'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' Sw Transitions',
            ['sw-transition/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' Sw Transition',
            ['sw-transition/create', 'SwTransition' => ['end_status_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-SwTransitions', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-SwTransitions ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getSwTransitions(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-swtransitions']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'sw-transition' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'sw-transition'
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'start_status_id',
    'value' => function ($model) {
        if ($rel = $model->getStartStatus()->one()) {
            return Html::a($rel->id, ['sw-status/view', 'id' => $rel->id,'workflow_id' => $rel->workflow_id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'start_status_workflow_id',
        'end_status_workflow_id',
        'created_by',
        'updated_by',
        'created_at',
        'updated_at',
        'deleted_at',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('SwTransitions0s'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' Sw Transitions0s',
            ['sw-transition/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' Sw Transitions0',
            ['sw-transition/create', 'SwTransitions0' => ['start_status_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-SwTransitions0s', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-SwTransitions0s ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getSwTransitions0s(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-swtransitions0s']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'sw-transition' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'sw-transition'
],
        'start_status_workflow_id',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'end_status_id',
    'value' => function ($model) {
        if ($rel = $model->getEndStatus()->one()) {
            return Html::a($rel->id, ['sw-status/view', 'id' => $rel->id,'workflow_id' => $rel->workflow_id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'end_status_workflow_id',
        'created_by',
        'updated_by',
        'created_at',
        'updated_at',
        'deleted_at',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('SwWorkflows'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' Sw Workflows',
            ['sw-workflow/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' Sw Workflow',
            ['sw-workflow/create', 'SwWorkflow' => ['initial_status_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-SwWorkflows', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-SwWorkflows ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getSwWorkflows(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-swworkflows']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'sw-workflow' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'sw-workflow'
],
        'id',
        'created_by',
        'updated_by',
        'created_at',
        'updated_at',
        'deleted_at',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['app\modules\workflow\models\SwStatus'],
    'active'  => true,
],[
    'content' => $this->blocks['SwTransitions'],
    'label'   => '<small>Sw Transitions <span class="badge badge-default">'.count($model->getSwTransitions()->asArray()->all()).'</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['SwTransitions0s'],
    'label'   => '<small>Sw Transitions0s <span class="badge badge-default">'.count($model->getSwTransitions0s()->asArray()->all()).'</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['SwWorkflows'],
    'label'   => '<small>Sw Workflows <span class="badge badge-default">'.count($model->getSwWorkflows()->asArray()->all()).'</span></small>',
    'active'  => false,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
