<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\modules\workflow\models\SwTransition $model
*/

$this->title = 'Sw Transition ' . $model->start_status_id;
$this->params['breadcrumbs'][] = ['label' => 'Sw Transitions', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->start_status_id, 'url' => ['view', 'start_status_id' => $model->start_status_id, 'start_status_workflow_id' => $model->start_status_workflow_id, 'end_status_id' => $model->end_status_id, 'end_status_workflow_id' => $model->end_status_workflow_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>

<?php echo $this->render('@app/modules/workflow/views/menu/_menu'); ?>

<div class="giiant-crud sw-transition-view">

    <div class="clearfix crud-navigation">
    <!-- menu buttons -->
    <div class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'start_status_id' => $model->start_status_id, 'start_status_workflow_id' => $model->start_status_workflow_id, 'end_status_id' => $model->end_status_id, 'end_status_workflow_id' => $model->end_status_workflow_id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
    </div>
    <div class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List SwTransitions'), ['index'], ['class'=>'btn btn-default']) ?>
    </div>

    </div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <?= $model->start_status_id ?>
        </div>

        <div class="panel-body">



    <?php $this->beginBlock('app\modules\workflow\models\SwTransition'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'start_status_id',
    'value' => ($model->getStartStatus()->one() ? Html::a($model->getStartStatus()->one()->id, ['sw-status/view', 'id' => $model->getStartStatus()->one()->id,'workflow_id' => $model->getStartStatus()->one()->workflow_id,]) : '<span class="label label-warning">?</span>'),
],
        'start_status_workflow_id',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'end_status_id',
    'value' => ($model->getEndStatus()->one() ? Html::a($model->getEndStatus()->one()->id, ['sw-status/view', 'id' => $model->getEndStatus()->one()->id,'workflow_id' => $model->getEndStatus()->one()->workflow_id,]) : '<span class="label label-warning">?</span>'),
],
        'end_status_workflow_id',
        'created_by',
        'updated_by',
        'created_at',
        'updated_at',
        'deleted_at',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'start_status_id' => $model->start_status_id, 'start_status_workflow_id' => $model->start_status_workflow_id, 'end_status_id' => $model->end_status_id, 'end_status_workflow_id' => $model->end_status_workflow_id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->start_status_id.'</b>',
    'content' => $this->blocks['app\modules\workflow\models\SwTransition'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
